version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      # day: "wednesday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
      - "Security"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    open-pull-requests-limit: 2
    target-branch: "master"
    ignore:
      # - version-update: semver-minor
      - version-update: semver-patch
