version: '3.7'

services:
  crypto-prices:
    image: crypto-prices
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      FETCH_CRYPTO_DATA_URL: https://api.alternative.me/v2/ticker/
    ports:
      - 8050:3000
