name: Build and test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x, 17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
